spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=clinic
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
    initialization-mode: always
    continue-on-error: false
    schema: classpath:init/schema.sql
    data: classpath:init/data.sql

logging:
  level:
    sql: info

server:
  port: 8094
